### ISSUE TITLE
how to use pagination?

### ISSUE THREAD

**Issue by achinverma** [Giphy/giphy-android-sdk-core#55]
Hi , i am using this library for gif, please anyone tell me how to implement pagination?

/// Trending Gifs
client.trending(MediaType.gif, null, null, null, new CompletionHandler<ListMediaResponse>() {
    @Override
    public void onComplete(ListMediaResponse result, Throwable e) {
        if (result == null) {
            // Do what you want to do with the error
        } else {
            if (result.getData() != null) {
                for (Media gif : result.getData()) {
                    Log.v("giphy", gif.getId());
                }
            } else {
                Log.e("giphy error", "No results found");
            }
        }
    }
}

**Comment by bogdantmm92** [comment]
Hello @achinverma, this is the method signature
```public Future trending(@Nullable MediaType type, @Nullable Integer limit,
                           @Nullable Integer offset, @Nullable RatingType rating,
                           @NonNull final CompletionHandler<ListMediaResponse> completionHandler);```

For example in order to fetch the top trending gifs, with limit=14 and offset=10, you'd call
```client.trending(MediaType.gif, 14, 10, null, new CompletionHandler() {```

Hope it helps! Let me know if you experience any problems when using the sdk.
