### ISSUE TITLE
Failed to build the signed apk

### ISSUE THREAD

**Issue by bingdow** [Giphy/giphy-android-sdk-core#61]
I'm trying to integrate Giphy SDK into the current project. I've followed the instructions from https://github.com/Giphy/giphy-android-sdk-core and it works like a charm. But it fails to generate signed apk with the following message:

`Warning:Exception while processing task java.io.IOException: Can't write [/Users/xxxxx/Documents/myApp/app/build/intermediates/transforms/proguard/facebook/release/jars/3/1f/main.jar] (Can't read [/Users/xxxxx/Documents/myApp/app/build/intermediates/transforms/FirebasePerformancePlugin/facebook/release/folders/1/4/9295f6fdf93ed7497ff128b73dc55529-classes(;;;;;;**.class)] (Can't read [com] (Can't read [giphy] (Can't read [sdk] (Can't read [core] (Can't read [network] (Can't read [response] (Can't read [ListMediaResponse.class] (Duplicate zip entry [com/giphy/sdk/core/network/response/ListMediaResponse.class])))))))))`

I've added the pro-guard rules but didn't work out.

```
-keep public class com.giphy.sdk.core.** { *; }
-dontwarn com.giphy.sdk.core.**
```

**Comment by bogdantmm92** [comment]
Thanks for using the sdk @bingdow. Could you please give sime details on how you fixed this issue? Could be helpful for people that will encounter a similar problem.

**Comment by bingdow** [comment]
@bogdantmm92 
Found myself misplaced the package declaration,

```
compile('com.giphy.sdk:core:1.0.0@aar') {
    transitive=true
}
```
I put this into the build.gradle file in the project instead of the module one. Though this has been mentioned on the GitHub page and I've read it, didn't expect it goes wrong just because of this.
Another question, since this should be placed in the module, why didn't Giphy developers put it as default?
