### ISSUE TITLE
Can't integrate with existing android project.

### ISSUE THREAD

**Issue by miinion** [Giphy/giphy-android-sdk-core#62]
I can't integrate this SDK to my existing android project. I did the step follow instruction but got the follow error message

"Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :giphy-android-sdk-core."

Please help, Thank you

**Comment by bogdantmm92** [comment]
Hello @miinion! Did you use the maven dependency or you cloned the repo and included it as a local dependency?

**Comment by miinion** [comment]
I get it work now, so I remove a local dependency, and use maven instead.
I misunderstand instruction, I did include both maven and a local dependency that why it caused an error.

thank you
