### ISSUE TITLE
RuntimeException when building a production apk with Proguard

### ISSUE THREAD

**Issue by franciscofranco** [Giphy/giphy-android-sdk-core#73]
It just crashes as soon as the app opens:

Caused by: java.lang.RuntimeException: Missing type parameter.
DefaultNetworkSession line 50
com.giphy.sdk.core.network.engine.DefaultNetworkSession.

This is all the stacktrace. The lib is correctly set up. I'm happy to provide more info if needed.

**Comment by bogdantmm92** [comment]
@franciscofranco could you try to add this into your proguard files and let me know if it works?
-keep class com.giphy.sdk.core.** { *; }
-dontwarn com.giphy.sdk.core.**

**Comment by franciscofranco** [comment]
No it doesn't work. I believe the trick is in GSON's proguard rules since that's what it's derping.

**Comment by franciscofranco** [comment]
I just fixed it. For GSON you need to add
-keepattributes Signature
for the default proguard configuration

**Comment by bogdantmm92** [comment]
Sorry for the hassle. Will fix this
